Repository brain-tec/stock-logistics-reporting, pull requests merged in 2021-09, with the labels that each got.

#61 [14.0][MIG] stock_quantity_history_location
  setup/stock_quantity_history_location/odoo/addons/stock_quantity_history_location
  setup/stock_quantity_history_location/setup.py
  stock_quantity_history_location/README.rst
  stock_quantity_history_location/__init__.py
  stock_quantity_history_location/__manifest__.py
  stock_quantity_history_location/i18n/it.po
  stock_quantity_history_location/i18n/ro.po
  stock_quantity_history_location/i18n/stock_quantity_history_location.pot
  stock_quantity_history_location/readme/CONSTRIBUTORS.rst
  stock_quantity_history_location/readme/DESCRIPTION.rst
  stock_quantity_history_location/readme/USAGE.rst
  stock_quantity_history_location/static/description/icon.png
  stock_quantity_history_location/static/description/index.html
  stock_quantity_history_location/static/src/js/inventory_report.js
  stock_quantity_history_location/tests/__init__.py
  stock_quantity_history_location/tests/common.py
  stock_quantity_history_location/tests/test_stock_quantity_history_location.py
  stock_quantity_history_location/wizards/__init__.py
  stock_quantity_history_location/wizards/stock_quantity_history.py
  stock_quantity_history_location/wizards/stock_quantity_history.xml
Labels: 14.0.project_to_553

#62 [14.0][MIG] stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/odoo/addons/stock_account_quantity_history_location
  setup/stock_account_quantity_history_location/setup.py
  stock_account_quantity_history_location/README.rst
  stock_account_quantity_history_location/__init__.py
  stock_account_quantity_history_location/__manifest__.py
  stock_account_quantity_history_location/i18n/fr.po
  stock_account_quantity_history_location/i18n/stock_account_quantity_history_location.pot
  stock_account_quantity_history_location/readme/CONSTRIBUTORS.rst
  stock_account_quantity_history_location/readme/DESCRIPTION.rst
  stock_account_quantity_history_location/static/description/icon.png
  stock_account_quantity_history_location/static/description/index.html
  stock_account_quantity_history_location/tests/__init__.py
  stock_account_quantity_history_location/tests/test_valuation_location.py
  stock_account_quantity_history_location/wizards/__init__.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.py
  stock_account_quantity_history_location/wizards/stock_quantity_history.xml
Labels: 14.0.project_to_553

#63 Syncing from upstream OCA/stock-logistics-reporting (13.0)
  README.md
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/stock_inventory_valuation_pivot/odoo/addons/stock_inventory_valuation_pivot
  setup/stock_inventory_valuation_pivot/setup.py
  stock_inventory_valuation_pivot/README.rst
  stock_inventory_valuation_pivot/__init__.py
  stock_inventory_valuation_pivot/__manifest__.py
  stock_inventory_valuation_pivot/i18n/es.po
  stock_inventory_valuation_pivot/i18n/stock_inventory_valuation_pivot.pot
  stock_inventory_valuation_pivot/readme/CONTRIBUTORS.rst
  stock_inventory_valuation_pivot/readme/DESCRIPTION.rst
  stock_inventory_valuation_pivot/readme/USAGE.rst
  stock_inventory_valuation_pivot/static/description/icon.png
  stock_inventory_valuation_pivot/static/description/index.html
  stock_inventory_valuation_pivot/views/stock_account_views.xml
Labels: 13.0

#64 Syncing from upstream OCA/stock-logistics-reporting (13.0)
  .travis.yml
  README.md
  delivery_line_sale_line_position/README.rst
  delivery_line_sale_line_position/__init__.py
  delivery_line_sale_line_position/__manifest__.py
  delivery_line_sale_line_position/i18n/delivery_line_sale_line_position.pot
  delivery_line_sale_line_position/models/__init__.py
  delivery_line_sale_line_position/models/stock_move.py
  delivery_line_sale_line_position/models/stock_move_line.py
  delivery_line_sale_line_position/readme/CONTRIBUTORS.rst
  delivery_line_sale_line_position/readme/DESCRIPTION.rst
  delivery_line_sale_line_position/report/report_deliveryslip.xml
  delivery_line_sale_line_position/static/description/icon.png
  delivery_line_sale_line_position/static/description/index.html
  delivery_line_sale_line_position/views/stock_move.xml
  delivery_line_sale_line_position/views/stock_picking.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_line_sale_line_position/odoo/addons/delivery_line_sale_line_position
  setup/delivery_line_sale_line_position/setup.py
  setup/stock_picking_group_by_partner_by_carrier_sale_line_position/odoo/addons/stock_picking_group_by_partner_by_carrier_sale_line_position
  setup/stock_picking_group_by_partner_by_carrier_sale_line_position/setup.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/README.rst
  stock_picking_group_by_partner_by_carrier_sale_line_position/__init__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/__manifest__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/i18n/stock_picking_group_by_partner_by_carrier_sale_line_position.pot
  stock_picking_group_by_partner_by_carrier_sale_line_position/models/__init__.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/models/stock_picking.py
  stock_picking_group_by_partner_by_carrier_sale_line_position/readme/CONTRIBUTORS.rst
  stock_picking_group_by_partner_by_carrier_sale_line_position/readme/DESCRIPTION.rst
  stock_picking_group_by_partner_by_carrier_sale_line_position/report/report_deliveryslip.xml
  stock_picking_group_by_partner_by_carrier_sale_line_position/static/description/icon.png
  stock_picking_group_by_partner_by_carrier_sale_line_position/static/description/index.html
Labels: 13.0

#65 Syncing from upstream OCA/stock-logistics-reporting (14.0)
  README.md
  delivery_line_sale_line_position/README.rst
  delivery_line_sale_line_position/__init__.py
  delivery_line_sale_line_position/__manifest__.py
  delivery_line_sale_line_position/i18n/delivery_line_sale_line_position.pot
  delivery_line_sale_line_position/models/__init__.py
  delivery_line_sale_line_position/models/stock_move.py
  delivery_line_sale_line_position/models/stock_move_line.py
  delivery_line_sale_line_position/readme/CONTRIBUTORS.rst
  delivery_line_sale_line_position/readme/CREDITS.rst
  delivery_line_sale_line_position/readme/DESCRIPTION.rst
  delivery_line_sale_line_position/report/report_deliveryslip.xml
  delivery_line_sale_line_position/static/description/icon.png
  delivery_line_sale_line_position/static/description/index.html
  delivery_line_sale_line_position/views/stock_move.xml
  delivery_line_sale_line_position/views/stock_picking.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/delivery_line_sale_line_position/odoo/addons/delivery_line_sale_line_position
  setup/delivery_line_sale_line_position/setup.py
Labels: 14.0
